version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paginaweb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234.abcd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  express-backend:
    build: ./express-backend
    container_name: express-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234.abcd
      DB_NAME: paginaweb
      JWT_SECRET: secreta123
    depends_on:
      - mysql

  backend-ia:
    build: ./backend-ia
    container_name: backend-ia
    restart: always
    ports:
      - "8000:8000"
    environment:
      OLLAMA_API_BASE: http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  mysql_data:
  ollama_data:
