version: "3.8"

services:
  react-app:
    image: paginaweb  # Nombre de la imagen
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"  # Para Vite
      - "3000:3000"  # Para Create React App
    volumes:
      - .:/app  # Monta el código fuente para hot reload
      - /app/node_modules  # Evita sobrescribir node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Hot reload en Docker
    command: ["npm", "run", "dev"]
