version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
